// Generated by CoffeeScript 1.4.0
(function() {

  define(['jQuery', 'Underscore', 'Backpack', 'text!template/ItemView.html'], function($, _, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      render: function() {
        var attrs;
        attrs = this.model.attributes;
        this.$el.html(this.template(attrs));
        return this;
      }
    });
  });

}).call(this);
