// Generated by CoffeeScript 1.4.0

/*
ToDo list application that uses localStorage
*/


(function() {
  var paths = {
    text: ['http://cdnjs.cloudflare.com/ajax/libs/require-text/2.0.3/text'],
    jQuery: ['http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min'],
    jQueryUI: ['http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min'],
    Underscore: ['http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min'],
    Backbone: ['http://cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.9/backbone-min'],
    'Backbone.localStorage': ['http://cdnjs.cloudflare.com/ajax/libs/backbone-localstorage.js/1.0/backbone.localStorage-min']
  };

  var shim = {
    text: {
      exports: 'text'
    },
    jQuery: {
      exports: '$'
    },
    jQueryUI: {
      deps: ['jQuery'],
      exports: '$'
    },
    Underscore: {
      exports: '_'
    },
    Backbone: {
      deps: ['Underscore', 'jQuery'],
      exports: 'Backbone'
    },
    'Backbone.localStorage': {
      deps: ['Backbone'],
      exports: 'Backbone'
    }
  };

  requirejs.config({ paths: paths, shim: shim });

  define(
    ['jQueryUI', 'Underscore', 'ListCollection', 'SongListView', 'PlayListContainerView'],
    function($, _, ListCollection, SongListView, PlayListContainerView){
      var pubsub = window.pubsub = _.extend({}, Backbone.Events);

      $('#showPlayListButton').on('click', function(){
        pubsub.trigger("SHOW_PLAY_LIST");
      });

      var collection = new ListCollection();
      new SongListView({ collection: collection });
//      collection.load();
      // dummy data
      collection.add([
        { name: 'hoge' },
        { name: 'fuga' },
        { name: 'aho' }
      ]);

      new PlayListContainerView();
  });
}).call(this);
