// Generated by CoffeeScript 1.4.0
(function() {

  define(['jQuery', 'Underscore', 'Backpack', 'ListModel', 'PlayListCollection', 'backpack/components/ListView', 'PlayItemView', 'backpack/plugins/Sortable', 'text!template/PlayListContainerView.html'], function($, _, Backpack, ListModel, PlayListCollection, ListView, PlayItemView, Sortable, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        "click .songListBtn": "close"
      },
      initialize: function() {
        var collection, view;
        this.render();
        collection = new PlayListCollection(null, {
          model: ListModel,
          subscribers: {
            SONG_FINISHED: 'onSongFinished'
          }
        });
        view = this.listView = new ListView({
          collection: collection,
          el: '#playListView',
          itemClass: PlayItemView,
          plugins: [Sortable],
          subscribers: {
            PLAYLIST_INDEX_UPDATED: this.onCurrentIndexUpdated
          },
          onCurrentIndexUpdated: function(index) {
            if (this._nowPlayingView) {
              this._nowPlayingView.$el.removeClass('now-playing');
            }
            if (index !== -1) {
              view = this._nowPlayingView = this.getChild(index);
              view.$el.addClass('now-playing');
            }
          }
        });
        view.render();
      },
      render: function() {
        this.$el.html(this.template());
        this.$el.dialog({
          autoOpen: false,
          width: $(window).width(),
          height: $(window).height()
        });
        return this;
      },
      open: function() {
        this.$el.dialog('open');
      },
      close: function() {
        this.$el.dialog('close');
      }
    });
  });

}).call(this);
