// Generated by CoffeeScript 1.4.0
(function() {

  define(['Underscore', 'Backbone', 'ItemView', 'text!template/PlayItemView.html', 'SoundPlayer'], function(_, Backbone, ItemView, viewTemplate, player) {
    return ItemView.extend({
      template: _.template(viewTemplate),
      events: {
        "click .playBtn": "onPlayButtonClicked",
        "click .removeBtn": "onRemoveButtonClicked"
      },
      onPlayButtonClicked: function() {
        player.play(this.model);
        Backbone.trigger("PLAYLIST_ITEM_SET_INDEX", this.model);
      },
      onRemoveButtonClicked: function() {
        if (confirm(_.template("Are you sure you want to delete '<%=title%>'?", this.model.attributes))) {
          Backbone.trigger("PLAYLIST_ITEM_REMOVED", this.model);
          this.model.destroy();
        }
      }
    });
  });

}).call(this);
