// Generated by CoffeeScript 1.6.2
(function() {
  define(['Underscore', 'Backpack', 'text!template/PlayItemView.html'], function(_, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .playBtn': 'onPlayButtonClicked',
        'click .removeBtn': 'onRemoveButtonClicked'
      },
      render: function() {
        var attrs;

        attrs = this.model.attributes;
        this.$el.html(this.template(attrs));
        return this;
      },
      onPlayButtonClicked: function() {
        Backbone.trigger('PLAYER_PLAY', this.model);
      },
      onRemoveButtonClicked: function() {
        if (confirm(_.template('Are you sure you want to delete "<%=title%>"?', this.model.attributes))) {
          this.model.destroy();
        }
      }
    });
  });

}).call(this);
