// Generated by CoffeeScript 1.4.0
(function() {

  define(['Underscore', 'Backpack', 'text!template/PlayItemView.html', 'SoundPlayer'], function(_, Backpack, viewTemplate, player) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .playBtn': 'onPlayButtonClicked',
        'click .removeBtn': 'onRemoveButtonClicked'
      },
      render: function() {
        var attrs;
        attrs = this.model.attributes;
        this.$el.html(this.template(attrs));
        return this;
      },
      onPlayButtonClicked: function() {
        player.play(this.model);
      },
      onRemoveButtonClicked: function() {
        if (confirm(_.template('Are you sure you want to delete "<%=title%>"?', this.model.attributes))) {
          this.model.destroy();
        }
      }
    });
  });

}).call(this);
