// Generated by CoffeeScript 1.4.0
(function() {

  define(['Underscore', 'Backpack', 'text!template/SongItemView.html'], function(_, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .playBtn': 'onPlayButtonClicked',
        'click .addBtn': 'onAddButtonClicked'
      },
      render: function() {
        var attrs;
        attrs = this.model.attributes;
        this.$el.html(this.template(attrs));
        return this;
      },
      onPlayButtonClicked: function() {
        var model;
        model = this.model.clone();
        Backbone.trigger('PLAYLIST_ITEM_INSERT', model);
        Backbone.trigger('PLAYER_PLAY', model);
        this.$el.addClass('playListAdded');
      },
      onAddButtonClicked: function() {
        Backbone.trigger('PLAYLIST_ITEM_ADD', this.model.clone());
        this.$el.addClass('playListAdded');
      }
    });
  });

}).call(this);
