// Generated by CoffeeScript 1.4.0
(function() {

  define(['Underscore', 'ItemView', 'text!template/SongItemView.html', 'SoundPlayer'], function(_, ItemView, viewTemplate, player) {
    return ItemView.extend({
      template: _.template(viewTemplate),
      events: {
        "click .playBtn": "onPlayButtonClicked",
        "click .addBtn": "onAddButtonClicked"
      },
      add2PlayList: function(isPlay) {
        Backbone.trigger("PLAYLIST_ITEM_ADDED", this.model.clone(), isPlay);
        this.$el.addClass('playListAdded');
      },
      onPlayButtonClicked: function() {
        player.play(this.model);
        this.add2PlayList(true);
      },
      onAddButtonClicked: function() {
        this.add2PlayList(false);
      }
    });
  });

}).call(this);
