// Generated by CoffeeScript 1.4.0
(function() {

  define(['SoundCloudAPI', 'Backpack'], function(SC, Backpack) {
    return Backpack.Class.extend({
      plugins: [Backpack.Singleton],
      initialize: function() {
        SC.initialize({
          client_id: '8ef8b80025535d68a51f4ee5c3343fc0',
          redirect_uri: 'http://kotaroshima.github.com/playlist/WebContent/callback.html'
        });
        this.domNode = document.getElementById('embedContainer');
        Backbone.on('PLAYER_PLAY', this.play, this);
        return this;
      },
      setup: function(callback) {
        SC.get('/tracks', {
          order: 'hotness',
          limit: 10,
          filter: 'streamable'
        }, callback);
      },
      play: function(model) {
        var url,
          _this = this;
        Backbone.trigger('SONG_STARTED', model);
        url = model.get('uri');
        if (!this._playerInit) {
          SC.oEmbed(url, {
            auto_play: true
          }, function(response) {
            var widget;
            _this.domNode.innerHTML = response.html;
            widget = _this._widget = SC.Widget($('#embedContainer IFRAME').get(0));
            widget.bind(SC.Widget.Events.FINISH, function() {
              Backbone.trigger('SONG_FINISHED');
            });
            _this._playerInit = true;
            widget.play();
          });
        } else {
          this._widget.load(url, {
            auto_play: true
          });
          this._widget.play();
        }
      },
      search: function(searchString, callback) {
        SC.get('/tracks', {
          q: searchString
        }, callback);
      }
    });
  });

}).call(this);
