// Generated by CoffeeScript 1.6.2
/*
* A view which displays now playing song
*/


(function() {
  define(['Underscore', 'Backpack', 'text!template/NowPlayingView.html'], function(_, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click #now-playing-back-button': 'onBackButtonClicked'
      },
      subscribers: {
        'PLAYER_PLAY': 'render'
      },
      render: function(model) {
        this.$el.html(this.template(model.attributes));
        return this;
      },
      onBackButtonClicked: function() {}
    });
  });

}).call(this);
