// Generated by CoffeeScript 1.6.2
/*
* A view to display/manage playlists
*/


(function() {
  var CLS_NOW_PLAYING, CLS_PLAYLIST_EDIT;

  CLS_NOW_PLAYING = 'now-playing';

  CLS_PLAYLIST_EDIT = 'playlist-edit';

  define(['jQueryUITouchPunch', 'Backpack', 'CurrentModelPlugin', 'SongItemView', 'text!template/PlayListContainerView.html'], function($, Backpack, CurrentModelPlugin, SongItemView, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .song-list-button': 'onSongListButtonClicked',
        'click .now-playing-button': 'onNowPlayingButtonClicked',
        'click .edit-button': 'onEditButtonClicked',
        'click .done-button': 'onDoneButtonClicked'
      },
      /*
      * Sets up playlist view
      */

      initialize: function(options) {
        var collection, view;

        Backpack.View.prototype.initialize.apply(this, arguments);
        this.render();
        collection = new Backpack.Collection(null, {
          model: Backpack.Model,
          plugins: [CurrentModelPlugin],
          subscribers: {
            SONG_STARTED: 'setCurrentModel',
            SONG_FINISHED: 'onSongFinished',
            PLAYLIST_ITEM_ADD: 'add',
            PLAYLIST_ITEM_INSERT: 'insertAfterCurrent'
          },
          publishers: {
            setCurrentIndex: 'PLAYLIST_INDEX_UPDATED'
          },
          onSongFinished: function() {
            var model;

            model = this.next();
            if (model) {
              Backbone.trigger('PLAYER_PLAY', model);
            }
          }
        });
        view = this.listView = new Backpack.EditableListView({
          collection: collection,
          itemView: SongItemView,
          itemOptions: {
            onSongItemClicked: function() {
              Backbone.trigger('PLAYER_PLAY', this.model);
              Backbone.trigger('SHOW_VIEW', 'nowPlayingView');
            }
          },
          subscribers: {
            PLAYLIST_INDEX_UPDATED: 'onCurrentIndexUpdated'
          },
          onCurrentIndexUpdated: function(index) {
            if (this._nowPlayingView) {
              this._nowPlayingView.$el.removeClass(CLS_NOW_PLAYING);
            }
            if (index >= 0) {
              this._nowPlayingView = this.getChild(index);
              this._nowPlayingView.$el.addClass(CLS_NOW_PLAYING);
            }
          }
        });
        view.render();
        this.$('#playlist-view').append(view.$el);
      },
      /*
      * Renders template HTML
      */

      render: function() {
        this.$el.html(this.template());
        return this;
      },
      /*
      * Click event handler for [Song List] button
      * When clicked, song list page opens
      */

      onSongListButtonClicked: function() {},
      onNowPlayingButtonClicked: function() {},
      /*
      * Click event handler for [Edit] button
      * Turns on edit mode when clicked
      */

      onEditButtonClicked: function() {
        this.listView.setEditable(true);
        this.$el.toggleClass(CLS_PLAYLIST_EDIT, true);
      },
      /*
      * Click event handler for [Edit] button
      * Turns off edit mode when clicked
      */

      onDoneButtonClicked: function() {
        this.listView.setEditable(false);
        this.$el.toggleClass(CLS_PLAYLIST_EDIT, false);
      }
    });
  });

}).call(this);
