// Generated by CoffeeScript 1.6.2
/*
* A view for each items in the play list
*/


(function() {
  var CLS_REMOVE_CONFIRM;

  CLS_REMOVE_CONFIRM = 'remove-confirm';

  define(['Underscore', 'Backpack', 'text!template/PlayItemView.html'], function(_, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .play-item-view': 'onPlayItemClicked',
        'click .delete-icon': 'onRemoveConfirmButtonClicked',
        'click .delete-button': 'onRemoveButtonClicked'
      },
      render: function() {
        this.$el.html(this.template(this.model.attributes));
        return this;
      },
      /*
      * Click event handler for play list item
      * Play the song corresponding to this view
      */

      onPlayItemClicked: function() {
        Backbone.trigger('PLAYER_PLAY', this.model);
        Backbone.trigger('SHOW_NOW_PLAYING_VIEW');
      },
      /*
      * Click event handler for remove confirm icon
      * switches to remove confirm mode
      */

      onRemoveConfirmButtonClicked: function() {
        var bRemoveConfirm;

        bRemoveConfirm = this.$el.hasClass(CLS_REMOVE_CONFIRM);
        this.$el.toggleClass(CLS_REMOVE_CONFIRM, !bRemoveConfirm);
        e.stopPropagation();
      },
      /*
      * Click event handler for [Remove] button
      * removes this item from play list
      */

      onRemoveButtonClicked: function() {
        this.model.destroy();
        e.stopPropagation();
      }
    });
  });

}).call(this);
