// Generated by CoffeeScript 1.6.2
/*
* A view for each items in the play list
*/


(function() {
  define(['Underscore', 'Backpack', 'text!template/PlayItemView.html'], function(_, Backpack, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click .play-item-view': 'onPlayItemClicked'
      },
      initialize: function(options) {
        this.render();
      },
      render: function() {
        var attr;

        attr = _.extend(this.model.attributes, {
          formatDuration: function(duration) {
            var h, ret;

            duration = Math.floor(duration / 1000);
            ret = '';
            h = parseInt(duration / 3600);
            if (h > 0) {
              ret += h + ':' + ('0' + parseInt((duration - 3600 * h) / 60)).slice(-2);
            } else {
              ret += parseInt(duration / 60);
            }
            return ret += ':' + ('0' + (duration % 60)).slice(-2);
          }
        });
        this.$el.html(this.template(attr));
        return this;
      },
      /*
      * Click event handler for play list item
      * Play the song corresponding to this view
      */

      onPlayItemClicked: function() {
        Backbone.trigger('PLAYER_PLAY', this.model);
        Backbone.trigger('SHOW_VIEW', 'nowPlayingView');
      }
    });
  });

}).call(this);
